"""attachments and ticket_status added

Revision ID: d6bf186aac1c
Revises: 4398819417ef
Create Date: 2026-03-05 20:17:44.161669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'd6bf186aac1c'
down_revision: Union[str, Sequence[str], None] = '4398819417ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_status_histories',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('from_status', postgresql.ENUM(
    "open", "pending", "resolved", "closed",
    name="ticket_status",
    create_type=False,
), nullable=False),
    sa.Column('to_status', postgresql.ENUM(
    "open", "pending", "resolved", "closed",
    name="ticket_status",
    create_type=False,
), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ticket_status_histories_org_id_created_at', 'ticket_status_histories', ['org_id', 'created_at'], unique=False)
    op.create_index('ix_ticket_status_histories_ticket_id_created_at', 'ticket_status_histories', ['ticket_id', 'created_at'], unique=False)
    op.create_table('attachments',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('comment_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('bucket', sa.String(length=63), nullable=True),
    sa.Column('s3_key', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attachments_comment', 'attachments', ['comment_id'], unique=False)
    op.create_index('ix_attachments_org_id_created_at', 'attachments', ['org_id', 'created_at'], unique=False)
    op.create_index('ix_attachments_ticket', 'attachments', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attachments_ticket', table_name='attachments')
    op.drop_index('ix_attachments_org_id_created_at', table_name='attachments')
    op.drop_index('ix_attachments_comment', table_name='attachments')
    op.drop_table('attachments')
    op.drop_index('ix_ticket_status_histories_ticket_id_created_at', table_name='ticket_status_histories')
    op.drop_index('ix_ticket_status_histories_org_id_created_at', table_name='ticket_status_histories')
    op.drop_table('ticket_status_histories')
    # ### end Alembic commands ###
