"""tickets added

Revision ID: faa8162077d8
Revises: 43986648bdfb
Create Date: 2026-03-04 16:43:28.432870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faa8162077d8'
down_revision: Union[str, Sequence[str], None] = '43986648bdfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PENDING', 'RESOLVED', 'CLOSED', name='ticket_status'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='ticket_priority'), nullable=False),
    sa.Column('latest_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_queue', 'tickets', ['org_id', 'assigned_to', 'status'], unique=False)
    op.create_index('ix_priority_filtering', 'tickets', ['org_id', 'priority'], unique=False)
    op.create_index('ix_recent_activity_ordering', 'tickets', ['org_id', 'latest_activity_at'], unique=False)
    op.create_index('ix_ticket_list_by_status', 'tickets', ['org_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ticket_list_by_status', table_name='tickets')
    op.drop_index('ix_recent_activity_ordering', table_name='tickets')
    op.drop_index('ix_priority_filtering', table_name='tickets')
    op.drop_index('ix_agent_queue', table_name='tickets')
    op.drop_table('tickets')
    # ### end Alembic commands ###
